services:
  # Dashboard Static Site
  - type: web
    name: lucine-dashboard
    env: static
    buildCommand: cd dashboard && npm install && npm run build
    staticPublishPath: dashboard/dist
    envVars:
      - key: NODE_VERSION
        value: 18
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
